database:
  enabled: true
  type: sqlite
  sqlite:
    path: "./app.db"
  show_sql: false
log:
  level: debug # 日志等级  debug,info,waring,error
  filename: ./logs/sms.log
e
server:
  addr: "0.0.0.0:8080"
  ip_extractor: "X-Real-IP"

App:
  # JWT配置
  JWT:
    Secret: "cf105e36-68ac-45be-be8a-348efcad4f1d"
    ExpiresHours: 168 # 7天
  Users:
    admin: "$2y$12$7DXcOiX1D59xNTIn5riUKusAPLP88LxxoczWmUT83MBj5EFznbp8a"  # 默认密码: admin123

  # 串口配置
  Serial:
    # 留空则自动检测，建议首次启动后手动指定
    Port: ""
